export type SeedStation = {
  station_code: string;
  station_name: string;
  city: string;
  latitude: number;
  longitude: number;
};

export type SeedTrain = {
  train_number: string;
  train_name: string;
  source_code: string;
  destination_code: string;
  total_seats: number;
  classes: string[];
  dep: string;
  arr: string;
  base_fare: number;
};

export const SEED_STATIONS: SeedStation[] = [
  { station_code: "NDLS", station_name: "New Delhi", city: "Delhi", latitude: 28.6425, longitude: 77.2192 },
  { station_code: "CSMT", station_name: "Chhatrapati Shivaji Maharaj Terminus", city: "Mumbai", latitude: 18.9401, longitude: 72.8354 },
  { station_code: "BCT", station_name: "Mumbai Central", city: "Mumbai", latitude: 18.969, longitude: 72.8193 },
  { station_code: "LTT", station_name: "Lokmanya Tilak Terminus", city: "Mumbai", latitude: 19.0699, longitude: 72.8911 },
  { station_code: "BDTS", station_name: "Bandra Terminus", city: "Mumbai", latitude: 19.062, longitude: 72.8407 },
  { station_code: "HWH", station_name: "Howrah Junction", city: "Kolkata", latitude: 22.5839, longitude: 88.3425 },
  { station_code: "SDAH", station_name: "Sealdah", city: "Kolkata", latitude: 22.5674, longitude: 88.3712 },
  { station_code: "KOAA", station_name: "Kolkata Chitpur", city: "Kolkata", latitude: 22.6025, longitude: 88.3764 },
  { station_code: "MAS", station_name: "MGR Chennai Central", city: "Chennai", latitude: 13.0827, longitude: 80.2757 },
  { station_code: "MS", station_name: "Chennai Egmore", city: "Chennai", latitude: 13.0784, longitude: 80.2608 },
  { station_code: "SBC", station_name: "KSR Bengaluru", city: "Bengaluru", latitude: 12.9776, longitude: 77.5713 },
  { station_code: "YPR", station_name: "Yesvantpur Junction", city: "Bengaluru", latitude: 13.0238, longitude: 77.5503 },
  { station_code: "SMVB", station_name: "Sir M. Visvesvaraya Terminal", city: "Bengaluru", latitude: 13.0033, longitude: 77.6547 },
  { station_code: "HYB", station_name: "Hyderabad Deccan", city: "Hyderabad", latitude: 17.385, longitude: 78.4867 },
  { station_code: "SC", station_name: "Secunderabad Junction", city: "Hyderabad", latitude: 17.4334, longitude: 78.5015 },
  { station_code: "KCG", station_name: "Kacheguda", city: "Hyderabad", latitude: 17.3879, longitude: 78.4983 },
  { station_code: "PUNE", station_name: "Pune Junction", city: "Pune", latitude: 18.5286, longitude: 73.8743 },
  { station_code: "ADI", station_name: "Ahmedabad Junction", city: "Ahmedabad", latitude: 23.0258, longitude: 72.5873 },
  { station_code: "JP", station_name: "Jaipur Junction", city: "Jaipur", latitude: 26.9196, longitude: 75.788 },
  { station_code: "LKO", station_name: "Lucknow Charbagh", city: "Lucknow", latitude: 26.831, longitude: 80.9231 },
  { station_code: "LJN", station_name: "Lucknow Junction", city: "Lucknow", latitude: 26.8322, longitude: 80.9214 },
  { station_code: "CNB", station_name: "Kanpur Central", city: "Kanpur", latitude: 26.4547, longitude: 80.3507 },
  { station_code: "PRYJ", station_name: "Prayagraj Junction", city: "Prayagraj", latitude: 25.4484, longitude: 81.8333 },
  { station_code: "BSB", station_name: "Varanasi Junction", city: "Varanasi", latitude: 25.3272, longitude: 82.986 },
  { station_code: "DDU", station_name: "Pt. Deen Dayal Upadhyaya Junction", city: "Mughalsarai", latitude: 25.2818, longitude: 83.1189 },
  { station_code: "GKP", station_name: "Gorakhpur Junction", city: "Gorakhpur", latitude: 26.7598, longitude: 83.3814 },
  { station_code: "PNBE", station_name: "Patna Junction", city: "Patna", latitude: 25.6019, longitude: 85.1376 },
  { station_code: "GAYA", station_name: "Gaya Junction", city: "Gaya", latitude: 24.8028, longitude: 84.9996 },
  { station_code: "DHN", station_name: "Dhanbad Junction", city: "Dhanbad", latitude: 23.7957, longitude: 86.4304 },
  { station_code: "TATA", station_name: "Tatanagar Junction", city: "Jamshedpur", latitude: 22.7667, longitude: 86.2 },
  { station_code: "RNC", station_name: "Ranchi Junction", city: "Ranchi", latitude: 23.3441, longitude: 85.324 },
  { station_code: "BBS", station_name: "Bhubaneswar", city: "Bhubaneswar", latitude: 20.2666, longitude: 85.8436 },
  { station_code: "CTC", station_name: "Cuttack Junction", city: "Cuttack", latitude: 20.4633, longitude: 85.8943 },
  { station_code: "PURI", station_name: "Puri Terminus", city: "Puri", latitude: 19.8135, longitude: 85.8312 },
  { station_code: "VSKP", station_name: "Visakhapatnam Junction", city: "Visakhapatnam", latitude: 17.7215, longitude: 83.2878 },
  { station_code: "BZA", station_name: "Vijayawada Junction", city: "Vijayawada", latitude: 16.5186, longitude: 80.62 },
  { station_code: "TPTY", station_name: "Tirupati", city: "Tirupati", latitude: 13.6288, longitude: 79.4192 },
  { station_code: "NGP", station_name: "Nagpur Junction", city: "Nagpur", latitude: 21.1527, longitude: 79.0882 },
  { station_code: "BPL", station_name: "Bhopal Junction", city: "Bhopal", latitude: 23.2683, longitude: 77.403 },
  { station_code: "RKMP", station_name: "Rani Kamlapati", city: "Bhopal", latitude: 23.2081, longitude: 77.4419 },
  { station_code: "GWL", station_name: "Gwalior Junction", city: "Gwalior", latitude: 26.2183, longitude: 78.1828 },
  { station_code: "VGLJ", station_name: "Virangana Lakshmibai Jhansi", city: "Jhansi", latitude: 25.4484, longitude: 78.5685 },
  { station_code: "AGC", station_name: "Agra Cantt", city: "Agra", latitude: 27.1593, longitude: 78.005 },
  { station_code: "MTJ", station_name: "Mathura Junction", city: "Mathura", latitude: 27.4924, longitude: 77.6737 },
  { station_code: "ET", station_name: "Itarsi Junction", city: "Itarsi", latitude: 22.6128, longitude: 77.7607 },
  { station_code: "JBP", station_name: "Jabalpur Junction", city: "Jabalpur", latitude: 23.167, longitude: 79.954 },
  { station_code: "R", station_name: "Raipur Junction", city: "Raipur", latitude: 21.2514, longitude: 81.6296 },
  { station_code: "BSP", station_name: "Bilaspur Junction", city: "Bilaspur", latitude: 22.0797, longitude: 82.1409 },
  { station_code: "GHY", station_name: "Guwahati", city: "Guwahati", latitude: 26.183, longitude: 91.75 },
  { station_code: "NJP", station_name: "New Jalpaiguri", city: "Siliguri", latitude: 26.6844, longitude: 88.4411 },
  { station_code: "UMB", station_name: "Ambala Cantt", city: "Ambala", latitude: 30.3609, longitude: 76.8286 },
  { station_code: "ASR", station_name: "Amritsar Junction", city: "Amritsar", latitude: 31.634, longitude: 74.8723 },
  { station_code: "JAT", station_name: "Jammu Tawi", city: "Jammu", latitude: 32.706, longitude: 74.8797 },
  { station_code: "SVDK", station_name: "Shri Mata Vaishno Devi Katra", city: "Katra", latitude: 32.9922, longitude: 74.9317 },
  { station_code: "CDG", station_name: "Chandigarh Junction", city: "Chandigarh", latitude: 30.702, longitude: 76.8197 },
  { station_code: "DDN", station_name: "Dehradun", city: "Dehradun", latitude: 30.3165, longitude: 78.0322 },
  { station_code: "HW", station_name: "Haridwar Junction", city: "Haridwar", latitude: 29.9457, longitude: 78.1642 },
  { station_code: "ERS", station_name: "Ernakulam Junction", city: "Kochi", latitude: 9.97, longitude: 76.287 },
  { station_code: "TVC", station_name: "Thiruvananthapuram Central", city: "Trivandrum", latitude: 8.4875, longitude: 76.9525 },
  { station_code: "CLT", station_name: "Kozhikode Main", city: "Calicut", latitude: 11.2464, longitude: 75.7797 },
  { station_code: "CBE", station_name: "Coimbatore Junction", city: "Coimbatore", latitude: 11.0016, longitude: 76.9628 },
  { station_code: "MDU", station_name: "Madurai Junction", city: "Madurai", latitude: 9.9197, longitude: 78.1118 },
  { station_code: "TPJ", station_name: "Tiruchchirappalli Junction", city: "Trichy", latitude: 10.7938, longitude: 78.6856 },
  { station_code: "MYS", station_name: "Mysuru Junction", city: "Mysore", latitude: 12.316, longitude: 76.6499 },
  { station_code: "UBL", station_name: "SSS Hubballi Junction", city: "Hubli", latitude: 15.3524, longitude: 75.1479 },
  { station_code: "MAO", station_name: "Madgaon Junction", city: "Goa", latitude: 15.2757, longitude: 73.9774 },
  { station_code: "MAQ", station_name: "Mangaluru Central", city: "Mangalore", latitude: 12.8654, longitude: 74.8426 },
  { station_code: "BKN", station_name: "Bikaner Junction", city: "Bikaner", latitude: 28.0167, longitude: 73.3119 },
  { station_code: "JU", station_name: "Jodhpur Junction", city: "Jodhpur", latitude: 26.2837, longitude: 73.0207 },
  { station_code: "AII", station_name: "Ajmer Junction", city: "Ajmer", latitude: 26.4525, longitude: 74.6399 },
  { station_code: "UDZ", station_name: "Udaipur City", city: "Udaipur", latitude: 24.5775, longitude: 73.6975 },
  { station_code: "KOTA", station_name: "Kota Junction", city: "Kota", latitude: 25.2235, longitude: 75.877 },
  { station_code: "RTM", station_name: "Ratlam Junction", city: "Ratlam", latitude: 23.3364, longitude: 75.037 },
  { station_code: "BRC", station_name: "Vadodara Junction", city: "Vadodara", latitude: 22.3107, longitude: 73.1812 },
  { station_code: "ST", station_name: "Surat", city: "Surat", latitude: 21.2049, longitude: 72.8407 },
  { station_code: "BVI", station_name: "Borivali", city: "Mumbai", latitude: 19.229, longitude: 72.8573 },
  { station_code: "TNA", station_name: "Thane", city: "Thane", latitude: 19.186, longitude: 72.9759 },
  { station_code: "KYN", station_name: "Kalyan Junction", city: "Kalyan", latitude: 19.2437, longitude: 73.1355 },
  { station_code: "MMR", station_name: "Manmad Junction", city: "Manmad", latitude: 20.2524, longitude: 74.4363 },
  { station_code: "BSL", station_name: "Bhusaval Junction", city: "Bhusaval", latitude: 21.0455, longitude: 75.7885 },
  { station_code: "SUR", station_name: "Solapur Junction", city: "Solapur", latitude: 17.6599, longitude: 75.9064 },
  { station_code: "WL", station_name: "Warangal", city: "Warangal", latitude: 17.9689, longitude: 79.5941 },
  { station_code: "GNT", station_name: "Guntur Junction", city: "Guntur", latitude: 16.2997, longitude: 80.4437 },
  { station_code: "RU", station_name: "Renigunta Junction", city: "Tirupati", latitude: 13.6489, longitude: 79.5133 },
  { station_code: "DBRG", station_name: "Dibrugarh", city: "Dibrugarh", latitude: 27.4728, longitude: 94.912 },
  { station_code: "AGTL", station_name: "Agartala", city: "Agartala", latitude: 23.795, longitude: 91.2722 },
  { station_code: "ROU", station_name: "Rourkela Junction", city: "Rourkela", latitude: 22.2334, longitude: 84.8774 },
  { station_code: "KGP", station_name: "Kharagpur Junction", city: "Kharagpur", latitude: 22.3435, longitude: 87.3228 },
  { station_code: "ASN", station_name: "Asansol Junction", city: "Asansol", latitude: 23.6845, longitude: 86.9746 },
  { station_code: "DGR", station_name: "Durgapur", city: "Durgapur", latitude: 23.4984, longitude: 87.3119 },
  { station_code: "MLDT", station_name: "Malda Town", city: "Malda", latitude: 25.0108, longitude: 88.1411 },
  { station_code: "KIR", station_name: "Katihar Junction", city: "Katihar", latitude: 25.554, longitude: 87.5724 },
  { station_code: "MFP", station_name: "Muzaffarpur Junction", city: "Muzaffarpur", latitude: 26.1226, longitude: 85.3906 },
  { station_code: "CPR", station_name: "Chhapra Junction", city: "Chhapra", latitude: 25.7811, longitude: 84.7339 },
  { station_code: "GD", station_name: "Gonda Junction", city: "Gonda", latitude: 27.1332, longitude: 81.9619 },
  { station_code: "MB", station_name: "Moradabad Junction", city: "Moradabad", latitude: 28.8386, longitude: 78.7733 },
  { station_code: "BE", station_name: "Bareilly Junction", city: "Bareilly", latitude: 28.347, longitude: 79.418 },
  { station_code: "DLI", station_name: "Old Delhi Junction", city: "Delhi", latitude: 28.6619, longitude: 77.228 },
  { station_code: "NZM", station_name: "Hazrat Nizamuddin", city: "Delhi", latitude: 28.5892, longitude: 77.253 },
  { station_code: "ANVT", station_name: "Anand Vihar Terminal", city: "Delhi", latitude: 28.6508, longitude: 77.3153 },
];

export const SEED_TRAINS: SeedTrain[] = [
  // 1-16: Vande Bharat Expresses
  { train_number: "22436", train_name: "Vande Bharat Express", source_code: "NDLS", destination_code: "BSB", total_seats: 530, classes: ["CC", "EC"], dep: "06:00", arr: "14:00", base_fare: 1750 },
  { train_number: "22435", train_name: "Vande Bharat Express Return", source_code: "BSB", destination_code: "NDLS", total_seats: 530, classes: ["CC", "EC"], dep: "15:00", arr: "23:00", base_fare: 1750 },
  { train_number: "22439", train_name: "Vande Bharat Express", source_code: "NDLS", destination_code: "SVDK", total_seats: 530, classes: ["CC", "EC"], dep: "06:00", arr: "14:00", base_fare: 1630 },
  { train_number: "22440", train_name: "Vande Bharat Express Return", source_code: "SVDK", destination_code: "NDLS", total_seats: 530, classes: ["CC", "EC"], dep: "15:00", arr: "23:00", base_fare: 1630 },
  { train_number: "20901", train_name: "Vande Bharat Express", source_code: "CSMT", destination_code: "ADI", total_seats: 530, classes: ["CC", "EC"], dep: "06:10", arr: "11:25", base_fare: 1420 },
  { train_number: "20902", train_name: "Vande Bharat Express Return", source_code: "ADI", destination_code: "CSMT", total_seats: 530, classes: ["CC", "EC"], dep: "15:00", arr: "20:25", base_fare: 1420 },
  { train_number: "20607", train_name: "Vande Bharat Express", source_code: "MAS", destination_code: "MYS", total_seats: 530, classes: ["CC", "EC"], dep: "05:50", arr: "12:20", base_fare: 1365 },
  { train_number: "20608", train_name: "Vande Bharat Express Return", source_code: "MYS", destination_code: "MAS", total_seats: 530, classes: ["CC", "EC"], dep: "13:05", arr: "19:30", base_fare: 1365 },
  { train_number: "20833", train_name: "Vande Bharat Express", source_code: "VSKP", destination_code: "SC", total_seats: 530, classes: ["CC", "EC"], dep: "05:45", arr: "14:15", base_fare: 1720 },
  { train_number: "20834", train_name: "Vande Bharat Express Return", source_code: "SC", destination_code: "VSKP", total_seats: 530, classes: ["CC", "EC"], dep: "15:00", arr: "23:30", base_fare: 1720 },
  { train_number: "22301", train_name: "Vande Bharat Express", source_code: "HWH", destination_code: "NJP", total_seats: 530, classes: ["CC", "EC"], dep: "05:55", arr: "13:25", base_fare: 1565 },
  { train_number: "22302", train_name: "Vande Bharat Express Return", source_code: "NJP", destination_code: "HWH", total_seats: 530, classes: ["CC", "EC"], dep: "15:05", arr: "22:35", base_fare: 1565 },
  { train_number: "20171", train_name: "Vande Bharat Express", source_code: "RKMP", destination_code: "NZM", total_seats: 530, classes: ["CC", "EC"], dep: "05:40", arr: "13:10", base_fare: 1665 },
  { train_number: "20172", train_name: "Vande Bharat Express Return", source_code: "NZM", destination_code: "RKMP", total_seats: 530, classes: ["CC", "EC"], dep: "14:40", arr: "22:10", base_fare: 1665 },
  { train_number: "20661", train_name: "Vande Bharat Express", source_code: "SBC", destination_code: "UBL", total_seats: 530, classes: ["CC", "EC"], dep: "05:45", arr: "10:45", base_fare: 1010 },
  { train_number: "20662", train_name: "Vande Bharat Express Return", source_code: "UBL", destination_code: "SBC", total_seats: 530, classes: ["CC", "EC"], dep: "13:15", arr: "18:20", base_fare: 1010 },

  // 17-34: Rajdhani Expresses
  { train_number: "12951", train_name: "Mumbai Rajdhani Express", source_code: "BCT", destination_code: "NDLS", total_seats: 620, classes: ["3A", "2A", "1A"], dep: "17:00", arr: "08:32", base_fare: 2150 },
  { train_number: "12952", train_name: "Mumbai Rajdhani Return", source_code: "NDLS", destination_code: "BCT", total_seats: 620, classes: ["3A", "2A", "1A"], dep: "16:55", arr: "08:35", base_fare: 2150 },
  { train_number: "12301", train_name: "Howrah Rajdhani Express", source_code: "HWH", destination_code: "NDLS", total_seats: 620, classes: ["3A", "2A", "1A"], dep: "16:50", arr: "10:05", base_fare: 2280 },
  { train_number: "12302", train_name: "Howrah Rajdhani Return", source_code: "NDLS", destination_code: "HWH", total_seats: 620, classes: ["3A", "2A", "1A"], dep: "16:55", arr: "09:55", base_fare: 2280 },
  { train_number: "12423", train_name: "Dibrugarh Rajdhani Express", source_code: "DBRG", destination_code: "NDLS", total_seats: 580, classes: ["3A", "2A", "1A"], dep: "20:55", arr: "10:30", base_fare: 2950 },
  { train_number: "12424", train_name: "Dibrugarh Rajdhani Return", source_code: "NDLS", destination_code: "DBRG", total_seats: 580, classes: ["3A", "2A", "1A"], dep: "16:10", arr: "07:00", base_fare: 2950 },
  { train_number: "12309", train_name: "Patna Rajdhani Express", source_code: "PNBE", destination_code: "NDLS", total_seats: 580, classes: ["3A", "2A", "1A"], dep: "19:25", arr: "07:40", base_fare: 1850 },
  { train_number: "12310", train_name: "Patna Rajdhani Return", source_code: "NDLS", destination_code: "PNBE", total_seats: 580, classes: ["3A", "2A", "1A"], dep: "17:10", arr: "05:15", base_fare: 1850 },
  { train_number: "12431", train_name: "Trivandrum Rajdhani", source_code: "TVC", destination_code: "NZM", total_seats: 580, classes: ["3A", "2A", "1A"], dep: "19:15", arr: "12:30", base_fare: 3350 },
  { train_number: "12432", train_name: "Trivandrum Rajdhani Return", source_code: "NZM", destination_code: "TVC", total_seats: 580, classes: ["3A", "2A", "1A"], dep: "06:16", arr: "23:35", base_fare: 3350 },
  { train_number: "12437", train_name: "Secunderabad Rajdhani", source_code: "SC", destination_code: "NZM", total_seats: 580, classes: ["3A", "2A", "1A"], dep: "12:45", arr: "10:30", base_fare: 2450 },
  { train_number: "12438", train_name: "Secunderabad Rajdhani Return", source_code: "NZM", destination_code: "SC", total_seats: 580, classes: ["3A", "2A", "1A"], dep: "15:35", arr: "13:35", base_fare: 2450 },
  { train_number: "12433", train_name: "Chennai Rajdhani Express", source_code: "MAS", destination_code: "NZM", total_seats: 580, classes: ["3A", "2A", "1A"], dep: "06:05", arr: "10:30", base_fare: 2780 },
  { train_number: "12434", train_name: "Chennai Rajdhani Return", source_code: "NZM", destination_code: "MAS", total_seats: 580, classes: ["3A", "2A", "1A"], dep: "15:35", arr: "20:45", base_fare: 2780 },
  { train_number: "12425", train_name: "Jammu Rajdhani Express", source_code: "NDLS", destination_code: "JAT", total_seats: 580, classes: ["3A", "2A", "1A"], dep: "20:40", arr: "05:00", base_fare: 1540 },
  { train_number: "12426", train_name: "Jammu Rajdhani Return", source_code: "JAT", destination_code: "NDLS", total_seats: 580, classes: ["3A", "2A", "1A"], dep: "21:25", arr: "05:55", base_fare: 1540 },
  { train_number: "12957", train_name: "Swarna Jayanti Rajdhani", source_code: "ADI", destination_code: "NDLS", total_seats: 580, classes: ["3A", "2A", "1A"], dep: "17:45", arr: "07:30", base_fare: 1890 },
  { train_number: "12958", train_name: "Swarna Jayanti Rajdhani Return", source_code: "NDLS", destination_code: "ADI", total_seats: 580, classes: ["3A", "2A", "1A"], dep: "19:55", arr: "09:30", base_fare: 1890 },

  // 35-44: Shatabdi Expresses
  { train_number: "12002", train_name: "Bhopal Shatabdi Express", source_code: "NDLS", destination_code: "RKMP", total_seats: 500, classes: ["CC", "EC"], dep: "06:00", arr: "14:40", base_fare: 1485 },
  { train_number: "12001", train_name: "Bhopal Shatabdi Return", source_code: "RKMP", destination_code: "NDLS", total_seats: 500, classes: ["CC", "EC"], dep: "15:15", arr: "23:50", base_fare: 1485 },
  { train_number: "12004", train_name: "Lucknow Shatabdi Express", source_code: "NDLS", destination_code: "LKO", total_seats: 500, classes: ["CC", "EC"], dep: "06:10", arr: "12:40", base_fare: 1165 },
  { train_number: "12003", train_name: "Lucknow Shatabdi Return", source_code: "LKO", destination_code: "NDLS", total_seats: 500, classes: ["CC", "EC"], dep: "15:35", arr: "22:20", base_fare: 1165 },
  { train_number: "12015", train_name: "Ajmer Shatabdi Express", source_code: "NDLS", destination_code: "AII", total_seats: 500, classes: ["CC", "EC"], dep: "06:10", arr: "12:55", base_fare: 1090 },
  { train_number: "12016", train_name: "Ajmer Shatabdi Return", source_code: "AII", destination_code: "NDLS", total_seats: 500, classes: ["CC", "EC"], dep: "15:55", arr: "22:40", base_fare: 1090 },
  { train_number: "12027", train_name: "Bengaluru Shatabdi Express", source_code: "MAS", destination_code: "SBC", total_seats: 500, classes: ["CC", "EC"], dep: "17:30", arr: "22:25", base_fare: 980 },
  { train_number: "12028", train_name: "Bengaluru Shatabdi Return", source_code: "SBC", destination_code: "MAS", total_seats: 500, classes: ["CC", "EC"], dep: "06:00", arr: "11:00", base_fare: 980 },
  { train_number: "12009", train_name: "Ahmedabad Shatabdi Express", source_code: "BCT", destination_code: "ADI", total_seats: 500, classes: ["CC", "EC"], dep: "06:20", arr: "12:45", base_fare: 1350 },
  { train_number: "12010", train_name: "Ahmedabad Shatabdi Return", source_code: "ADI", destination_code: "BCT", total_seats: 500, classes: ["CC", "EC"], dep: "15:10", arr: "21:45", base_fare: 1350 },

  // 45-50: Duronto & Superfast Flagships
  { train_number: "12290", train_name: "Nagpur Duronto Express", source_code: "NGP", destination_code: "CSMT", total_seats: 700, classes: ["SL", "3A", "2A", "1A"], dep: "20:40", arr: "08:05", base_fare: 1120 },
  { train_number: "12289", train_name: "Mumbai Duronto Express", source_code: "CSMT", destination_code: "NGP", total_seats: 700, classes: ["SL", "3A", "2A", "1A"], dep: "20:15", arr: "07:20", base_fare: 1120 },
  { train_number: "12621", train_name: "Tamil Nadu Express", source_code: "MAS", destination_code: "NDLS", total_seats: 850, classes: ["SL", "3A", "2A", "1A"], dep: "22:00", arr: "06:30", base_fare: 840 },
  { train_number: "12622", train_name: "Tamil Nadu Express Return", source_code: "NDLS", destination_code: "MAS", total_seats: 850, classes: ["SL", "3A", "2A", "1A"], dep: "21:05", arr: "06:15", base_fare: 840 },
  { train_number: "12627", train_name: "Karnataka Express", source_code: "SBC", destination_code: "NDLS", total_seats: 850, classes: ["SL", "3A", "2A"], dep: "19:20", arr: "09:00", base_fare: 860 },
  { train_number: "12628", train_name: "Karnataka Express Return", source_code: "NDLS", destination_code: "SBC", total_seats: 850, classes: ["SL", "3A", "2A"], dep: "20:20", arr: "12:00", base_fare: 860 },
];
